### ISSUE TITLE
Error While tns run android

### ISSUE THREAD

**Issue by LakshmiEvana** [gethuman/nativescript-sidedrawer#2]
I got these below errors while 'tns run android'.

![image](https://cloud.githubusercontent.com/assets/17317992/21416025/6af52b5c-c835-11e6-87c3-8195a0a2a74b.png)

After these errors build succesfully completed but app not opened in my device.

**Comment by demym** [comment]
Exactly the same happens to me. On Android builds successfullly (with those errors) but is not being installed. On IOS it installs, but then it crashes when app is open.

**Comment by roblav96** [comment]
I can confirm these errors on my end.

A fix will be published in < 3hrs.

**Comment by roblav96** [comment]
@LakshmiEvana @demym Can either of you update and confirm this has been resolved?

**Comment by emin93** [comment]
![bildschirmfoto 2016-12-24 um 20 17 21](https://cloud.githubusercontent.com/assets/5310475/21468531/06e09196-ca16-11e6-85cb-6f9862a696f9.png)

Still have an issue, but not sure if it's related to this :/

**Comment by roblav96** [comment]
@emin93 you need to add the native declarations to your project

**Comment by emin93** [comment]
@roblav96 Ah that makes sense, will try later and give feedback if it worked.

**Comment by LakshmiEvana** [comment]
Noo @roblav96.
Same errors while 'tns run android'

**Comment by hamidhomapour** [comment]
Same errors happen for me.

**Comment by EliuFlorez** [comment]
Hello friends, no solution yet? My error is as follows.

![sidedrawer-error](https://cloud.githubusercontent.com/assets/784787/22806776/fd56f378-eef9-11e6-9ec2-e9b8895aed08.jpg)

It's as if the aar com.mikepenz:materialdrawer:5.7.0@aar package is not being added to your libs

`android {
	productFlavors {
		"nativescriptsidedrawer" {
			dimension "nativescriptsidedrawer"
		}
	}
}

dependencies {
	compile('com.mikepenz:materialdrawer:5.7.0@aar') {
		transitive = true
	}
}`

**Comment by roblav96** [comment]
@EliuFlorez Try removing your node modules folder and platforms folder and reinstall. Also make sure any drawables (icons) are properly installed.

**Comment by behiunforgiven** [comment]
Is this problem solved?
I have the same problem.

**Comment by sarvagayatri** [comment]
same errors.

`node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3395,32):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3398,37):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3398,64):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3399,40):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3400,40):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3401,45):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3402,44):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3403,40):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3405,33):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3406,29):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3407,33):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3407,66):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3408,33):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3408,69):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3409,51):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(3409,78):
error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/index.d.ts(3,15): error TS2306: File 'G:/Na
tive Script/SideDrawerTest/node_modules/nativescript-sidedrawer/com.mikepenz.mat
erialdrawer.d.ts' is not a module.`

**Comment by roblav96** [comment]
I'll have to update typescript declarations

**Comment by longfay** [comment]
same error
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(1409,29): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(1409,48): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(1411,23): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(1414,30): error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(1414,48): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(1416,30): error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(1417,39): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(1418,30): error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(1418,56): error TS2503: Cannot find namespace 'java'.

**Comment by roblav96** [comment]
@LakshmiEvana Fixed with https://github.com/gethuman/nativescript-sidedrawer/commit/f2bf34b6b9371933fa5b9cdcf86adec69a52d6c6
